"""Generate the physical design vectors of placement map contract 5.

Contract 5 lets a layout carry a key order, a time partition and index methods. Two libraries that
parse those keys differently build different tables from one signed document, and nothing raises -
each of them created a table successfully. So every rule gets a shared case, in the two families
that can reach it:

- ``schema/014``-``018``: the DDL a designed layout renders to, byte for byte, in both dialects,
  plus the renderer's refusals of a design made for another dialect. A map carries no dialect
  (§7), so "a BRIN index rendered for ClickHouse" is legal to load and refused where the dialect is
  known - the renderer - and nowhere earlier.
- ``errors/052``-``072``: the map-stage refusals, each with the one defect it names.

The statements come from the reference implementation, with the usual limitation - generated by
the thing they verify - and the ``schema/`` family's mitigation: ``test_schema_vectors_live.py``
executes every statement against a real PostgreSQL and a real ClickHouse, so a vector whose bytes
no engine accepts cannot be frozen.

This tool writes only the directories it names and never touches another vector. Rerunning it
rewrites exactly those, which is how a change to one of them is reviewed as a diff.

    python conformance/tools/physical_vectors.py --i-am-changing-the-contract
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "python" / "src"))

import sde  # noqa: E402
from sde.errors import EngineError, MapError  # noqa: E402
from sde.testing.loader import model_from_neutral  # noqa: E402

VECTORS = ROOT / "conformance" / "vectors"
PROJECT = "5" * 32

# One model for every case: four unrelated entities, so four colocation groups, each placed on its
# own. `Reading` is the ClickHouse shape the design section of the contract uses as its example.
MODEL: dict[str, Any] = {
    "entities": [
        {
            "name": "Ledger",
            "fields": [
                {"name": "account", "type": "string"},
                {"name": "amount", "type": "int64"},
                {"name": "memo", "type": "string", "nullable": True},
                {"name": "posted", "type": "date"},
            ],
            "key": ["account", "posted"],
        },
        {
            "name": "Reading",
            "fields": [
                {"name": "at", "type": "timestamptz"},
                {"name": "humidity", "type": "int32"},
                {"name": "station", "type": "string"},
                {"name": "temperature", "type": "float64"},
            ],
            "key": ["station", "at"],
        },
        {
            "name": "Archive",
            "fields": [
                {"name": "day", "type": "date"},
                {"name": "sensor", "type": "string"},
                {"name": "total", "type": "int64"},
            ],
            "key": ["sensor", "day"],
        },
        {
            "name": "Event",
            "fields": [
                {"name": "id", "type": "int64"},
                {"name": "kind", "type": "string"},
                {"name": "seen", "type": "timestamp"},
            ],
            "key": ["id", "seen"],
        },
    ],
}

POSTGRES_COLUMNS = {
    "Archive": {"day": "date", "sensor": "text", "total": "bigint"},
    "Event": {"id": "bigint", "kind": "text", "seen": "timestamp"},
    "Ledger": {"account": "text", "amount": "bigint", "memo": "text", "posted": "date"},
    "Reading": {
        "at": "timestamptz",
        "humidity": "integer",
        "station": "text",
        "temperature": "double precision",
    },
}
CLICKHOUSE_COLUMNS = {
    "Archive": {"day": "Date32", "sensor": "String", "total": "Int64"},
    "Event": {"id": "Int64", "kind": "String", "seen": "DateTime64(6)"},
    "Ledger": {
        "account": "String",
        "amount": "Int64",
        "memo": "Nullable(String)",
        "posted": "Date32",
    },
    "Reading": {
        "at": "DateTime64(6, 'UTC')",
        "humidity": "Int32",
        "station": "String",
        "temperature": "Float64",
    },
}
TABLES = {"Archive": "archive", "Event": "event", "Ledger": "ledger", "Reading": "reading"}


def _model() -> sde.LogicalModel:
    return model_from_neutral(MODEL)


def _layout(entity: str, dialect: str, **design: Any) -> dict[str, Any]:
    columns = CLICKHOUSE_COLUMNS if dialect == "clickhouse" else POSTGRES_COLUMNS
    return {
        "tables": {entity: TABLES[entity]},
        "columns": {entity: dict(columns[entity])},
        **design,
    }


def _map(sources: dict[str, dict[str, Any]], *, contract: int = 5) -> dict[str, Any]:
    """A valid unsigned map placing each of the four groups on its own source."""
    model = _model()
    groups: dict[str, Any] = {}
    for group in sde.colocation_groups(model):
        (entity,) = group.members
        source = sources.get(entity) or {
            "id": f"{entity}@pg",
            "engine": "pg-main",
            "layout": _layout(entity, "postgres"),
        }
        groups[group.name] = {"source": source, **({"write_epoch": 1} if contract >= 4 else {})}
    document: dict[str, Any] = {
        "contract": contract,
        "model_version": model.version,
        "map_version": 1,
        "groups": groups,
    }
    if contract >= 4:
        document["project_id"] = PROJECT
    return document


def _source(entity: str, engine: str, dialect: str, **design: Any) -> dict[str, Any]:
    suffix = {"clickhouse": "ch", "orderbook": "ob", "postgres": "pg"}[dialect]
    return {
        "id": f"{entity}@{suffix}",
        "engine": engine,
        "layout": _layout(entity, dialect, **design),
    }


def _write(directory: Path, files: dict[str, Any]) -> None:
    if directory.exists():
        shutil.rmtree(directory)
    directory.mkdir(parents=True)
    for name, body in files.items():
        (directory / name).write_text(json.dumps(body, indent=2, ensure_ascii=True) + "\n")


# --- schema/ ---------------------------------------------------------------------------------


def _render(document: dict[str, Any], materialization: str, dialect: str) -> list[str] | Exception:
    model = _model()
    placement = sde.load_map(document, model=model)
    for group in placement.groups.values():
        for material in group.all():
            if material.id == materialization:
                keys = {entity: list(model.entity(entity).key) for entity in material.layout.tables}
                try:
                    return list(sde.schema_statements(material.layout, keys=keys, dialect=dialect))
                except EngineError as exc:
                    return exc
    raise AssertionError(f"no materialisation {materialization!r}")


def _case(
    document: dict[str, Any], materialization: str, dialect: str, why: str, **refusal: str
) -> dict[str, Any]:
    rendered = _render(document, materialization, dialect)
    case: dict[str, Any] = {
        "materialization": materialization,
        "dialect": dialect,
        "fixed": sde.schema_is_fixed(dialect),
    }
    if refusal:
        assert isinstance(rendered, EngineError), (materialization, dialect, rendered)
        assert refusal["match"] in str(rendered), (refusal["match"], str(rendered))
        case.update(error="EngineError", match=refusal["match"])
    else:
        assert isinstance(rendered, list), (materialization, dialect, rendered)
        case["statements"] = rendered
    case["why"] = why
    return case


def schema_vectors() -> list[str]:
    written: list[str] = []
    model = sde.neutral_declaration(_model())

    key_order = _map(
        {
            "Ledger": _source(
                "Ledger", "pg-main", "postgres", key_order={"Ledger": ["posted", "account"]}
            ),
            "Reading": _source(
                "Reading", "ch-1", "clickhouse", key_order={"Reading": ["at", "station"]}
            ),
        }
    )
    cases = [
        _case(
            key_order,
            "Ledger@pg",
            "postgres",
            "PRIMARY KEY in the physical order the layout gives, not the declared one. The key is "
            "still the model's - the same two columns, so the same uniqueness and the same `get` - "
            "and only which prefix the index can seek by has moved.",
        ),
        _case(
            key_order,
            "Reading@ch",
            "clickhouse",
            "ORDER BY in the physical order the layout gives. In ClickHouse the key order decides "
            "which prefixes prune granules; `ReplacingMergeTree` deduplicates on the whole ORDER "
            "BY "
            "tuple, which is the same set of columns in either order, so the rows are the same "
            "rows.",
        ),
    ]
    _write(
        VECTORS / "schema" / "014-a-key-order-reorders-the-physical-key",
        {"model.json": model, "map.json": key_order, "cases.json": cases},
    )
    written.append("schema/014")

    partitions = _map(
        {
            "Archive": _source(
                "Archive",
                "ch-1",
                "clickhouse",
                partition_by={"Archive": {"field": "day", "granularity": "year"}},
            ),
            "Ledger": _source(
                "Ledger",
                "ch-1",
                "clickhouse",
                partition_by={"Ledger": {"field": "posted", "granularity": "day"}},
            ),
            "Reading": _source(
                "Reading",
                "ch-1",
                "clickhouse",
                key_order={"Reading": ["at", "station"]},
                partition_by={"Reading": {"field": "at", "granularity": "month"}},
            ),
        }
    )
    cases = [
        _case(
            partitions,
            "Reading@ch",
            "clickhouse",
            "PARTITION BY toYYYYMM of a key column, before ORDER BY - the order ClickHouse's "
            "grammar "
            "requires. The function names are the ones the catalogue reports back in "
            "`system.tables.partition_key`, which is what the adapters' verification parses.",
        ),
        _case(
            partitions,
            "Ledger@ch",
            "clickhouse",
            "`day` is toDate. On a `date` field the column is Date32, and toDate of it is a "
            "partition value only: the stored date is untouched whatever range it is in.",
        ),
        _case(
            partitions,
            "Archive@ch",
            "clickhouse",
            "`year` is toYear. Three granularities and no week, because toStartOfWeek has a mode "
            "and a closed vocabulary has none.",
        ),
    ]
    _write(
        VECTORS / "schema" / "015-a-clickhouse-partition-follows-the-key",
        {"model.json": model, "map.json": partitions, "cases.json": cases},
    )
    written.append("schema/015")

    skipping = _map(
        {
            "Reading": _source(
                "Reading",
                "ch-1",
                "clickhouse",
                indexes=[
                    {
                        "entity": "Reading",
                        "name": "reading_temperature",
                        "columns": ["temperature"],
                        "method": "minmax",
                        "granularity": 4,
                    },
                    {
                        "entity": "Reading",
                        "name": "reading humidity",
                        "columns": ["humidity"],
                        "method": "set",
                        "granularity": 2,
                        "max_rows": 100,
                    },
                    {
                        "entity": "Reading",
                        "name": "reading_bloom",
                        "columns": ["station"],
                        "method": "bloom_filter",
                        "granularity": 1,
                    },
                ],
            ),
        }
    )
    cases = [
        _case(
            skipping,
            "Reading@ch",
            "clickhouse",
            "Data-skipping indexes inline in CREATE TABLE, because `CREATE TABLE IF NOT EXISTS` "
            "never "
            "adds one to an existing table and a separate ALTER would be a mutation over every "
            "part. "
            "Rendered in code point order of the index name whatever order the document gives - "
            "the "
            "document lists them out of order on purpose - and the name with a space is quoted by "
            "the same escaper as every other identifier. `set` carries its max_rows as set(N).",
        ),
        _case(
            skipping,
            "Reading@ch",
            "postgres",
            "The same layout through the PostgreSQL renderer is refused, and that is the point of "
            "pinning it: a map carries no dialect, so a ClickHouse design loads cleanly and the "
            "renderer is the first place that can say it was made for another engine.",
            match="ClickHouse data-skipping index",
        ),
    ]
    _write(
        VECTORS / "schema" / "016-clickhouse-data-skipping-indexes",
        {"model.json": model, "map.json": skipping, "cases.json": cases},
    )
    written.append("schema/016")

    postgres = _map(
        {
            "Ledger": _source(
                "Ledger",
                "pg-main",
                "postgres",
                indexes=[
                    {
                        "entity": "Ledger",
                        "name": "ledger_posted_brin",
                        "columns": ["posted"],
                        "method": "brin",
                    },
                    {"entity": "Ledger", "name": "ledger_amount", "columns": ["amount"]},
                    {
                        "entity": "Ledger",
                        "name": "ledger_memo",
                        "columns": ["memo", "amount"],
                        "method": "btree",
                    },
                ],
            ),
        }
    )
    cases = [
        _case(
            postgres,
            "Ledger@pg",
            "postgres",
            "A B-tree renders exactly the bytes every earlier map produced, with no USING clause, "
            "whether the method is absent or written out; BRIN renders USING brin. Statements in "
            "code point order of the index name, and the document lists them out of order.",
        ),
        _case(
            postgres,
            "Ledger@pg",
            "clickhouse",
            "The same layout through the ClickHouse renderer is refused: it has no B-tree and no "
            "BRIN, and its primary index is ORDER BY.",
            match="has no B-tree",
        ),
    ]
    _write(
        VECTORS / "schema" / "017-postgres-brin-and-btree",
        {"model.json": model, "map.json": postgres, "cases.json": cases},
    )
    written.append("schema/017")

    refused = _map(
        {
            "Reading": _source(
                "Reading",
                "ch-1",
                "clickhouse",
                partition_by={"Reading": {"field": "at", "granularity": "month"}},
            ),
            "Event": _source("Event", "ob-1", "orderbook", key_order={"Event": ["seen", "id"]}),
        }
    )
    cases = [
        _case(
            refused,
            "Reading@ch",
            "postgres",
            "PostgreSQL does not render partitioning in this version: every partition would have "
            "to exist before a row arrived, which is a lifecycle this product does not manage. An "
            "unpartitioned table under a map that says otherwise would be a silent drop.",
            match="PostgreSQL partitioning is not rendered",
        ),
        _case(
            refused,
            "Event@ob",
            "orderbook",
            "An engine whose schema is fixed in its own source renders nothing - and a physical "
            "design aimed at it is refused rather than dropped, because 'nothing' is only the "
            "right "
            "answer when nothing was asked for.",
            match="schema is fixed in its own source",
        ),
    ]
    _write(
        VECTORS / "schema" / "018-a-design-for-another-dialect-is-refused-by-the-renderer",
        {"model.json": model, "map.json": refused, "cases.json": cases},
    )
    written.append("schema/018")
    return written


# --- errors/ ---------------------------------------------------------------------------------


def _refusal(name: str, document: dict[str, Any], match: str, why: str) -> str:
    model = _model()
    try:
        sde.load_map(document, model=model)
    except MapError as exc:
        assert match in str(exc), (name, match, str(exc))
    else:
        raise AssertionError(f"{name}: the reference accepted the map")
    _write(
        VECTORS / "errors" / name,
        {
            "model.json": sde.neutral_declaration(model),
            "map.json": document,
            "expected.json": {"error": "MapError", "match": match, "stage": "map", "why": why},
        },
    )
    return "errors/" + name[:3]


def _reading(contract: int = 5, **design: Any) -> dict[str, Any]:
    return _map({"Reading": _source("Reading", "ch-1", "clickhouse", **design)}, contract=contract)


def _index(**fields: Any) -> dict[str, Any]:
    return {"entity": "Reading", "name": "reading_index", "columns": ["temperature"], **fields}


def error_vectors() -> list[str]:
    written = [
        _refusal(
            "052-a-key-order-that-is-not-a-permutation",
            _reading(key_order={"Reading": ["at"]}),
            "cannot add, drop or replace a column",
            "A key order reorders the key and does nothing else. Dropping `station` here would "
            "leave ClickHouse deduplicating on `at` alone, so two stations reporting in the same "
            "microsecond would collapse into one row - a different identity from the model's, "
            "applied silently. Needs the model, so it is checked where the model is supplied.",
        ),
        _refusal(
            "053-a-key-order-that-names-a-column-twice",
            _reading(key_order={"Reading": ["station", "station"]}),
            "names a column twice",
            "Refused without the model, because no key has a column twice.",
        ),
        _refusal(
            "054-a-key-order-for-an-entity-without-a-table",
            _reading(key_order={"Ledger": ["account", "posted"]}),
            "has no table in this layout",
            "The layout places Reading. A key order for an entity it does not hold is either a "
            "mistake in the producer or a document assembled from two layouts, and neither should "
            "be applied.",
        ),
        _refusal(
            "055-a-partition-outside-the-key",
            _reading(partition_by={"Reading": {"field": "humidity", "granularity": "month"}}),
            "which is not in the key",
            "ReplacingMergeTree collapses rows of one key only inside one partition. Partitioned "
            "on "
            "a column outside the key, two writes of one key can land in two partitions and stay "
            "two rows physically for ever - measured on ClickHouse 24.8: FINAL hid the duplicate "
            "only because do_not_merge_across_partitions_select_final was 0, and after OPTIMIZE "
            "FINAL both rows remained. This is a data rule, not a performance one.",
        ),
        _refusal(
            "056-a-partition-on-a-key-column-that-is-not-a-time",
            _reading(partition_by={"Reading": {"field": "station", "granularity": "month"}}),
            "a time partition needs one of",
            "`station` is in the key, so duplicates are safe - and toYYYYMM of a string is not a "
            "time partition. The granularities only mean something for a date or a zoned "
            "timestamp.",
        ),
        _refusal(
            "057-a-partition-on-a-timestamp-without-a-zone",
            _map(
                {
                    "Event": _source(
                        "Event",
                        "ch-1",
                        "clickhouse",
                        partition_by={"Event": {"field": "seen", "granularity": "month"}},
                    ),
                }
            ),
            "a time partition needs one of",
            "`seen` is in the key and is a time - and a timestamp without a zone is still refused. "
            "Its ClickHouse column (DateTime64(6)) carries no zone, so the month a value falls "
            "into "
            "follows the server's configured timezone, and a server reconfigured later would put "
            "the same key into another partition: two rows for ever, the outcome errors/055 exists "
            "to prevent, by another road. A session's session_timezone does not move it (measured, "
            "24.8); the server's zone is documented to. date and timestamptz depend on nothing.",
        ),
        _refusal(
            "058-a-partition-granularity-outside-the-vocabulary",
            _reading(partition_by={"Reading": {"field": "at", "granularity": "week"}}),
            "it is one of",
            "No week: toStartOfWeek depends on a mode (Sunday or Monday first) and a closed "
            "vocabulary has no modes. A week that meant two different things in two deployments "
            "is the ambiguity the list exists to remove.",
        ),
        _refusal(
            "059-a-partition-that-carries-an-expression",
            _reading(
                partition_by={
                    "Reading": {"field": "at", "granularity": "month", "expression": "toYYYYMM(at)"}
                }
            ),
            "must be exactly",
            "Exactly two keys. Nothing in a map is pasted into DDL, and an extra key that one "
            "library ignored and another rendered would be two tables from one document.",
        ),
        _refusal(
            "060-an-index-method-outside-the-vocabulary",
            _reading(indexes=[_index(method="hash", granularity=1)]),
            "the methods are",
            "Five methods in two dialects. A method name no library renders would be ignored by "
            "one and refused by another.",
        ),
        _refusal(
            "061-a-data-skipping-index-without-a-granularity",
            _reading(indexes=[_index(method="minmax")]),
            "needs an integer granularity from 1 to 1024",
            "A data-skipping index summarises a number of granules per entry and ClickHouse needs "
            "the number. No default: a default chosen by a library is a performance decision taken "
            "by whichever version happens to be installed.",
        ),
        _refusal(
            "062-a-data-skipping-index-over-no-granules",
            _reading(indexes=[_index(method="minmax", granularity=0)]),
            "needs an integer granularity from 1 to 1024",
            "Zero granules per entry is not an index.",
        ),
        _refusal(
            "063-a-set-index-without-a-limit",
            _reading(indexes=[_index(method="set", granularity=1, max_rows=0)]),
            "needs an integer max_rows from 1 to 65536",
            "set(0) means unlimited in ClickHouse, which is an unbounded memory commitment per "
            "index entry, so zero is outside the range rather than a default.",
        ),
        _refusal(
            "064-a-data-skipping-index-over-two-columns",
            _reading(
                indexes=[
                    _index(method="minmax", granularity=1, columns=["temperature", "humidity"])
                ]
            ),
            "summarises exactly one column",
            "One column per data-skipping index in this vocabulary. A tuple expression would be "
            "an expression, and nothing in a map is an expression.",
        ),
        _refusal(
            "065-a-granularity-on-an-index-that-has-none",
            _reading(indexes=[_index(method="brin", granularity=4)]),
            "granularity belongs to data-skipping indexes",
            "BRIN has pages_per_range, not a ClickHouse granularity. A key that means nothing for "
            "the method is refused rather than ignored.",
        ),
        _refusal(
            "066-a-null-granularity-is-still-a-key",
            _reading(indexes=[_index(granularity=None)]),
            "granularity belongs to data-skipping indexes",
            "Presence, not value. The first version of the reference asked `is not None`, which "
            "accepted this document, while TypeScript asked whether the key was there and refused "
            "it - one map, two answers. Found while porting, before anything was released.",
        ),
        _refusal(
            "067-max-rows-on-an-index-that-is-not-a-set",
            _reading(indexes=[_index(method="minmax", granularity=1, max_rows=10)]),
            "max_rows belongs to set indexes",
            "Only set(N) has a size.",
        ),
        _refusal(
            "068-an-index-on-a-column-the-layout-does-not-have",
            _reading(indexes=[_index(method="minmax", granularity=1, columns=["pressure"])]),
            "does not have in this layout",
            "Checkable without the model, from the layout's own columns. Otherwise the engine "
            "refuses at CREATE INDEX, in the client's process, naming a column rather than the "
            "cause.",
        ),
        _refusal(
            "069-two-indexes-with-one-name",
            _reading(
                indexes=[
                    _index(method="minmax", granularity=1),
                    _index(method="minmax", granularity=2, columns=["humidity"]),
                ]
            ),
            "reuses the index name",
            "`CREATE INDEX IF NOT EXISTS` would keep the first and skip the second without a word.",
        ),
        _refusal(
            "070-an-index-key-this-format-does-not-define",
            _reading(indexes=[_index(method="minmax", granularity=1, unique=True)]),
            "has keys this format does not define",
            "Closed vocabulary: an unknown key is refused, not ignored.",
        ),
        _refusal(
            "071-an-index-method-in-a-contract-4-map",
            _map(
                {
                    "Ledger": _source(
                        "Ledger",
                        "pg-main",
                        "postgres",
                        indexes=[
                            {
                                "entity": "Ledger",
                                "name": "ledger_posted",
                                "columns": ["posted"],
                                "method": "brin",
                            }
                        ],
                    )
                },
                contract=4,
            ),
            "which placement map contract 5",
            "The loosening that bumped the contract. A contract-4 library ignores `method` and "
            "builds a B-tree from this document while a contract-5 one builds BRIN, so the key is "
            "refused in a document declaring 4 - the producer forgot to raise the number.",
        ),
        _refusal(
            "072-a-key-order-in-a-contract-4-map",
            _map(
                {
                    "Ledger": _source(
                        "Ledger", "pg-main", "postgres", key_order={"Ledger": ["posted", "account"]}
                    )
                },
                contract=4,
            ),
            "key_order is map contract 5",
            "A contract-4 library would order the key as declared and a contract-5 one as written "
            "here: one document, two tables.",
        ),
        _refusal(
            "073-a-null-key-order-is-not-an-absent-one",
            _reading(key_order=None),
            "key_order maps an entity to a list of its key columns",
            "Absent means no design; `null` is a key whose value is not one. The first port read "
            "the key with `?? {}`, which treats the two alike, while the reference read it with "
            "`.get(key, {})`, which does not - one document accepted in one language and refused "
            "in the other, the `or` against `??` divergence this suite has caught before.",
        ),
    ]
    return written


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--i-am-changing-the-contract", action="store_true", required=True)
    parser.parse_args()
    written = schema_vectors() + error_vectors()
    print(f"Wrote {len(written)} physical design vectors: {', '.join(written)}")


if __name__ == "__main__":
    main()
