"""Generate the ``schema/`` vectors: a layout in, the exact DDL out.

Section 10 of the format contract recorded this family as missing, and said why the gap was
tolerable: *"The gap costs nothing while one library claims those tiers and everything on the day
two do, so the vectors are written before a second claim is accepted, not after."* This is that day.
Raising TypeScript to Tier 2 is the second claim, so the family exists before the claim, not after
it.

What it pins, and each of these is a way two libraries can agree on a map and disagree on a
database:

- **column order**, which is code point order and not the platform's string order. This is the
  second call site of the comparator that produced the ``canonical/`` family; the first was object
  keys in the IR. ``003`` is the case no ASCII layout can reach.
- **key order**, which is *declared* order and never sorted, because in ClickHouse it becomes
  ``ORDER BY`` and decides which prefixes prune granules.
- **the refusals**: an unknown dialect, an index in a dialect with no B-tree, a key naming a column
  the layout does not have, a layout with no columns, and a caller that supplied no key.
- **which engines take DDL from us at all**, through ``fixed`` on every case.

The statements come from the reference implementation, with the usual limitation - generated by the
thing they verify - and one mitigation that the other families do not have:
``python/tests/test_schema_vectors_live.py`` executes every statement in this family against a real
PostgreSQL and a real ClickHouse. A vector whose bytes no engine accepts would be a frozen mistake,
and that test is what makes it impossible.

    python conformance/tools/schema_vectors.py --i-am-changing-the-contract
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "python" / "src"))

import sde  # noqa: E402
from sde.errors import EngineError  # noqa: E402
from sde.testing.loader import model_from_neutral  # noqa: E402

VECTORS = ROOT / "conformance" / "vectors" / "schema"


def _neutral(model: sde.LogicalModel) -> dict[str, Any]:
    return sde.neutral_declaration(model)


def _layout_doc(layout: sde.PhysicalLayout) -> dict[str, Any]:
    doc: dict[str, Any] = {
        "tables": dict(layout.tables),
        "columns": {e: dict(c) for e, c in layout.columns.items()},
    }
    if layout.indexes:
        doc["indexes"] = [dict(i) for i in layout.indexes]
    return doc


def _map(model: sde.LogicalModel, materializations: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """A minimal, valid, unsigned map placing every group with one source each.

    A whole map rather than a bare layout document, and that is the decision worth stating: the
    input then reaches the renderer through the *same* loader production uses, instead of through a
    second parser written for the vectors. It also means a case can only pin DDL for a layout this
    library would accept in the first place.
    """
    groups: dict[str, Any] = {}
    for group in sde.colocation_groups(model):
        spec = materializations[group.name]
        groups[group.name] = {"source": spec}
    return {
        "contract": sde.CONTRACT,
        "model_version": model.version,
        "map_version": 1,
        "groups": groups,
    }


def _write(name: str, model: sde.LogicalModel, raw_map: dict[str, Any], cases: list[Any]) -> None:
    out = VECTORS / name
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / "model.json").write_text(json.dumps(_neutral(model), indent=2) + "\n", encoding="utf-8")
    (out / "map.json").write_text(json.dumps(raw_map, indent=2) + "\n", encoding="utf-8")
    (out / "cases.json").write_text(json.dumps(cases, indent=2) + "\n", encoding="utf-8")
    print(f"  wrote schema/{name}")


def _shop() -> sde.LogicalModel:
    """Two entities in one colocation group, one of them with a composite key and a relation.

    Declared neutrally rather than through the decorator so that the field order in the document is
    the one written here - which is *not* sorted, so a library that trusted the document's order
    instead of sorting would produce different DDL and this family would catch it.
    """
    sde.clear_registry()
    return model_from_neutral(
        {
            "entities": [
                {
                    "name": "Order",
                    "fields": [
                        {"name": "tenant", "type": "uuid"},
                        {"name": "id", "type": "uuid"},
                        {"name": "total", "type": "decimal(12,2)"},
                        {"name": "placed_at", "type": "timestamptz"},
                    ],
                    "key": ["tenant", "id"],
                    "residency": "EU",
                },
                {
                    "name": "Payment",
                    "fields": [
                        {"name": "id", "type": "uuid"},
                        {"name": "amount", "type": "decimal(12,2)"},
                        {"name": "paid_at", "type": "timestamp"},
                    ],
                    "key": ["id"],
                },
            ],
            "relations": [{"name": "order", "from": "Payment", "to": "Order"}],
            "atomic": [["Order", "Payment"]],
        }
    )


def _astral() -> sde.LogicalModel:
    """Column names that expose UTF-16 order against code point order.

    Above U+FFFF the two disagree: an astral character is a surrogate pair starting at 0xD800, so
    UTF-16 order puts it *before* U+E000 while code point order puts it after. Every layout in this
    family other than this one is ASCII, and no ASCII layout can tell the two comparators apart.
    """
    sde.clear_registry()
    return model_from_neutral(
        {
            "entities": [
                {
                    "name": "Astral",
                    "fields": [
                        {"name": "id", "type": "uuid"},
                        {"name": "a", "type": "string"},
                        {"name": "\U0001f600", "type": "string"},
                        {"name": "\ue000", "type": "string"},
                    ],
                    "key": ["id"],
                }
            ],
            "relations": [],
            "atomic": [],
        }
    )


def _orderbook() -> sde.LogicalModel:
    """The one shape our own orderbook engine stores, declared as a model.

    Not a coincidence that it reads like the engine's own header: the relationship inverts for a
    fixed-schema engine, so either the client's model *is* this shape or the group cannot be placed
    there at all.
    """
    sde.clear_registry()
    return model_from_neutral(
        {
            "entities": [
                {
                    "name": "Depth",
                    "fields": [
                        {"name": name, "type": kind}
                        for name, kind in sde.ORDERBOOK_SHAPE.items()
                    ],
                    "key": list(sde.ORDERBOOK_KEY),
                }
            ],
            "relations": [],
            "atomic": [],
        }
    )


def _statements(layout: sde.PhysicalLayout, model: sde.LogicalModel, group: str, dialect: str):
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    keys = {name: list(model.entity(name).key) for name in members.members}
    return list(sde.schema_statements(layout, keys=keys, dialect=dialect))


def _refusal(fn: Any, match: str) -> dict[str, str]:
    """Check that the reference refuses, and that its message contains ``match``.

    The vector stores the substring rather than the whole sentence, exactly as the ``errors/``
    family does: a library may say more, in any language it likes, and may not say less. Written as
    a check rather than a capture so that the substring in the vector is one a person chose, and so
    that generating this family cannot quietly record a *different* refusal than the one intended.
    """
    try:
        fn()
    except EngineError as exc:
        if match not in str(exc):
            raise SystemExit(f"the reference refused with {str(exc)!r}, which does not contain {match!r}")
        return {"error": "EngineError", "match": match}
    raise SystemExit(f"expected a refusal containing {match!r} and got none")


def _one() -> None:
    model = _shop()
    group = "Order"
    pg = sde.default_layout(model, next(g for g in sde.colocation_groups(model) if g.name == group))
    raw = _map(model, {group: {"id": "Order@pg", "engine": "pg-main", "layout": _layout_doc(pg)}})
    cases = [
        {
            "materialization": "Order@pg",
            "dialect": "postgres",
            "fixed": False,
            "statements": _statements(pg, model, group, "postgres"),
            "why": (
                "Columns are sorted by name and the key is not: 'tenant' comes before 'id' in the "
                "PRIMARY KEY because that is the order the model declared, and a sorted key would "
                "silently reorder a composite index. The tables come out in code point order of "
                "the entity name, which is why 'Order' precedes 'Payment' here and why a library "
                "iterating the document's own order would drift the day a planner emitted them "
                "differently."
            ),
        },
        {
            "materialization": "Order@pg",
            "dialect": "clickhouse",
            "fixed": False,
            **_refusal(lambda: _statements(pg, model, group, "clickhouse"), "no B-tree to put them in"),
            "why": (
                "The fifth issuing rule, from the library's side. A layout carrying an index is "
                "valid, signs correctly and loads correctly, and rendering it for an engine with "
                "no B-tree is where it stops being applicable - a map that verifies and cannot be "
                "applied. The control plane asks this library rather than reimplementing the "
                "answer, so this refusal is what stops such a map being issued at all."
            ),
        },
    ]
    _write("001-postgres-a-group-of-two-entities", model, raw, cases)


def _two() -> None:
    model = _shop()
    group = "Order"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    ch = sde.default_layout(model, members, dialect="clickhouse")
    raw = _map(model, {group: {"id": "Order@ch", "engine": "ch-1", "layout": _layout_doc(ch)}})
    cases = [
        {
            "materialization": "Order@ch",
            "dialect": "clickhouse",
            "fixed": False,
            "statements": _statements(ch, model, group, "clickhouse"),
            "why": (
                "ReplacingMergeTree and ORDER BY, not a primary key: a MergeTree does not enforce "
                "uniqueness, so the engine keeps the newest row for a key and collapses the rest "
                "at merge time. ORDER BY carries the *declared* order because it decides which "
                "prefixes of the key can prune granules - so sorting it would change the physical "
                "performance of the table while leaving the map looking identical. The default "
                "layout emits no indexes for this dialect, which is why there are none to refuse "
                "here."
            ),
        },
        {
            "materialization": "Order@ch",
            "dialect": "postgres",
            "fixed": False,
            "statements": _statements(ch, model, group, "postgres"),
            "why": (
                "The same layout through the other renderer, and it produces statements rather "
                "than a refusal - because the column *types* in a layout are already this "
                "dialect's spelling and a renderer does not read them. Worth pinning precisely "
                "because it is the case that looks like it should fail: what would fail is running "
                "the result, which is why the dialect is an argument the caller takes from its "
                "engine adapter and never guesses."
            ),
        },
    ]
    _write("002-clickhouse-replacing-merge-tree", model, raw, cases)


def _three() -> None:
    model = _astral()
    group = "Astral"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    pg = sde.default_layout(model, members)
    raw = _map(model, {group: {"id": "Astral@pg", "engine": "pg-main", "layout": _layout_doc(pg)}})
    cases = [
        {
            "materialization": "Astral@pg",
            "dialect": "postgres",
            "fixed": False,
            "statements": _statements(pg, model, group, "postgres"),
            "why": (
                "Expected column order: 'a', 'id', U+E000, U+1F600. A library sorting by UTF-16 "
                "code unit - which is what JavaScript's default comparator does - puts U+1F600 "
                "before U+E000, because a surrogate pair starts at 0xD800. Nothing in an ASCII "
                "layout can see the difference, and the consequence is two CREATE TABLE "
                "statements for one signed map. This is the DDL renderer's copy of the defect the "
                "canonical/ family was created for; that one was object keys in the IR."
            ),
        }
    ]
    _write("003-columns-in-code-point-order", model, raw, cases)


def _four() -> None:
    model = _orderbook()
    group = "Depth"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    fixed = sde.default_layout(model, members, dialect="orderbook")
    raw = _map(
        model, {group: {"id": "Depth@ob", "engine": "ob-1", "layout": _layout_doc(fixed)}}
    )
    cases = [
        {
            "materialization": "Depth@ob",
            "dialect": "orderbook",
            "fixed": True,
            "statements": [],
            "why": (
                "No statements, and `fixed` is what tells that apart from 'no tables in this "
                "layout'. An engine whose schema is fixed in its own source takes no DDL from us; "
                "running nothing is the correct action, and a caller *reporting* what the client "
                "must do has a different sentence to write. A library that threw here would push "
                "the branch out to every caller."
            ),
        }
    ]
    _write("004-a-fixed-schema-engine-renders-nothing", model, raw, cases)


def _five() -> None:
    model = _shop()
    group = "Order"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    pg = sde.default_layout(model, members)
    raw = _map(model, {group: {"id": "Order@pg", "engine": "pg-main", "layout": _layout_doc(pg)}})
    keys = {name: list(model.entity(name).key) for name in members.members}
    cases = [
        {
            "materialization": "Order@pg",
            "dialect": "mysql",
            **_refusal(
                lambda: sde.schema_statements(pg, keys=keys, dialect="mysql"), "no DDL for dialect"
            ),
            "why": (
                "Refusing rather than falling back to ANSI. A statement that looks right on the "
                "wrong engine creates a table with the wrong storage semantics, and the client "
                "finds out from their data rather than from an error. `fixed` is absent from this "
                "case on purpose: asking whether an unknown engine imposes its own schema has to "
                "refuse too, because answering 'no' would claim that engine takes DDL from us."
            ),
            "fixed_error": {"error": "EngineError", "match": "unknown dialect"},
        }
    ]
    _write("005-an-unknown-dialect-is-refused", model, raw, cases)


def _six() -> None:
    """A key column the layout does not have, and a layout with no columns at all."""
    model = _shop()
    group = "Order"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    ch = sde.default_layout(model, members, dialect="clickhouse")
    keys = {name: list(model.entity(name).key) for name in members.members}

    thin_columns = {e: dict(c) for e, c in ch.columns.items()}
    del thin_columns["Order"]["tenant"]
    thin = sde.PhysicalLayout(tables=dict(ch.tables), columns=thin_columns, indexes=())

    empty = sde.PhysicalLayout(tables=dict(ch.tables), columns={}, indexes=())

    raw = _map(model, {group: {"id": "Order@ch", "engine": "ch-1", "layout": _layout_doc(thin)}})
    cases = [
        {
            "materialization": "Order@ch",
            "dialect": "clickhouse",
            "fixed": False,
            **_refusal(
                lambda: sde.schema_statements(thin, keys=keys, dialect="clickhouse"),
                "names columns the layout does not have",
            ),
            "why": (
                "The key becomes ORDER BY, so a key column that is not in the table is a statement "
                "that will not parse - refused here rather than by the engine, because the engine's "
                "message names a column and not the cause. PostgreSQL would refuse the same layout "
                "for its own reason; the two are separate refusals because ORDER BY and PRIMARY "
                "KEY are separate mechanisms."
            ),
        },
        {
            "materialization": "Order@ch",
            "dialect": "clickhouse",
            "fixed": False,
            "layout_columns": {},
            **_refusal(
                lambda: sde.schema_statements(empty, keys=keys, dialect="clickhouse"),
                "gives no columns for",
            ),
            "why": (
                "A layout with tables and no columns is not a layout this library can apply. It is "
                "reachable: `columns` is optional in the document because the routing families do "
                "not need it, so a hand-written map naming tables alone loads cleanly and fails "
                "here. `layout_columns` replaces the materialisation's columns in the runner, "
                "which is the one place a case edits its own input - there is no other way to "
                "express 'the map said nothing about columns' once the loader has parsed it."
            ),
        },
    ]
    _write("006-a-key-column-the-layout-does-not-have", model, raw, cases)


def _seven() -> None:
    model = _shop()
    group = "Order"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    pg = sde.default_layout(model, members)
    raw = _map(model, {group: {"id": "Order@pg", "engine": "pg-main", "layout": _layout_doc(pg)}})
    cases = [
        {
            "materialization": "Order@pg",
            "dialect": "postgres",
            "fixed": False,
            "keys": {"Order": ["tenant", "id"], "Payment": []},
            **_refusal(
                lambda: sde.schema_statements(
                    pg, keys={"Order": ["tenant", "id"], "Payment": []}, dialect="postgres"
                ),
                "a table without one cannot be addressed",
            ),
            "why": (
                "Reachable from a caller and not from a model: an entity declaring no key is "
                "refused at the model stage (errors/026), so the keys this renderer receives are "
                "assembled by whoever calls it - the control plane does, per group. A table with "
                "no PRIMARY KEY cannot be addressed, migrated or verified, so emitting one would "
                "produce a group that looks placed and cannot be moved. `keys` in a case replaces "
                "the mapping derived from the model, which is the only way to reach this."
            ),
        }
    ]
    _write("007-the-caller-supplied-no-key", model, raw, cases)


def _eight() -> None:
    """Compatibility views: what can stand under a table's old name, and what cannot."""
    model = _shop()
    group = "Order"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    pg = sde.default_layout(model, members)
    ch = sde.default_layout(model, members, dialect="clickhouse")
    raw = _map(model, {group: {"id": "Order@pg", "engine": "pg-main", "layout": _layout_doc(pg)}})
    raw["groups"][group]["derived"] = [
        {"id": "Order@ch", "engine": "ch-1", "layout": _layout_doc(ch), "lag_budget_ms": 30000}
    ]

    renamed = {"Order": "orders_v1", "Payment": "payments_v1"}
    same = dict(pg.tables)

    def views(
        layout: sde.PhysicalLayout,
        was: dict[str, str],
        dialect: str,
        expect: dict[str, list[str]],
    ) -> dict[str, Any]:
        """The rendered views, with the *reasons* pinned as substrings a person chose.

        `create` and `drop` are statements - bytes an engine receives - so they are pinned exactly.
        A reason is diagnostics, so it is pinned the way the `errors/` family pins a message: a
        library may say more, in any language it likes, and may not say less. `match` is a list
        here because the useful reasons carry two claims - which name moved, and what the query has
        to become - and one substring cannot straddle both.
        """
        result = sde.compatibility_views(layout, was=was, dialect=dialect)
        got = {entity: why for entity, why in result.not_possible}
        if sorted(got) != sorted(expect):
            raise SystemExit(f"not_possible is {sorted(got)}, the case expects {sorted(expect)}")
        for entity, wanted in expect.items():
            for fragment in wanted:
                if fragment not in got[entity]:
                    raise SystemExit(f"{entity}: {got[entity]!r} does not contain {fragment!r}")
        return {
            "create": list(result.create),
            "drop": list(result.drop),
            "not_possible": [
                {"entity": entity, "match": expect[entity]} for entity, _ in result.not_possible
            ],
            "complete": result.complete,
        }

    cases = [
        {
            "materialization": "Order@pg",
            "dialect": "postgres",
            "fixed": False,
            "statements": _statements(pg, model, group, "postgres"),
            "views": {"was": renamed, **views(pg, renamed, "postgres", {})},
            "why": (
                "The tables were called something else in the engine the group left, so a view can "
                "stand under each old name. CREATE OR REPLACE VIEW, because PostgreSQL has no "
                "CREATE VIEW IF NOT EXISTS - measured against the server, and the first draft of "
                "the renderer emitted the form that is a syntax error. Columns are listed rather "
                "than SELECT *, in the layout's order, so a query reading them by position sees "
                "what CREATE TABLE produced."
            ),
        },
        {
            "materialization": "Order@ch",
            "dialect": "clickhouse",
            "fixed": False,
            "statements": _statements(ch, model, group, "clickhouse"),
            "views": {
                "was": same,
                **views(
                    ch,
                    same,
                    "clickhouse",
                    {
                        "Order": ["the name is not what moved", "FINAL", "counted twice"],
                        "Payment": ["the name is not what moved", "FINAL"],
                    },
                ),
            },
            "why": (
                "Both engines derive the table name from the entity name and nothing else, so "
                "after a move between them the name is not what changed - the dialect is, and "
                "there is no old name for a view to occupy. That is the ordinary answer in this "
                "engine set, and the useful part of it is the sentence: a query moved here "
                "verbatim must read FINAL, because the table is a ReplacingMergeTree and without "
                "it a row written twice under one key is counted twice until a background merge - "
                "measured, two rows against one."
            ),
        },
    ]
    _write("008-compatibility-views-on-the-target", model, raw, cases)


def _nine() -> None:
    """A document whose columns are out of order, and both renderings sorted anyway.

    The case that makes the two sorts separately mutable. Before this vector the view renderer read
    its column order off the document, on the stated grounds that the document was already sorted -
    it is not, because a foreign-key column is appended per relation - so an entity with a relation
    had a view and a table listing the same columns in different orders, and a hand-written query
    moved onto the view read them by position and got different values. The test meant to hold that
    property used a fixture with no relations.
    """
    model = _shop()
    group = "Order"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    pg = sde.default_layout(model, members)
    doc = _layout_doc(pg)
    # Reversed on purpose. A planner emits them in one order; a client hand-writing a map in the
    # no-account mode emits whatever they typed, and both must produce one database.
    doc["columns"] = {e: dict(reversed(list(c.items()))) for e, c in doc["columns"].items()}
    raw = _map(model, {group: {"id": "Order@pg", "engine": "pg-main", "layout": doc}})

    scrambled = sde.PhysicalLayout(
        tables=dict(pg.tables),
        columns={e: dict(reversed(list(c.items()))) for e, c in pg.columns.items()},
        indexes=tuple(dict(i) for i in pg.indexes),
    )
    renamed = {"Order": "orders_v1", "Payment": "payments_v1"}
    result = sde.compatibility_views(scrambled, was=renamed, dialect="postgres")
    cases = [
        {
            "materialization": "Order@pg",
            "dialect": "postgres",
            "fixed": False,
            "statements": _statements(scrambled, model, group, "postgres"),
            "views": {
                "was": renamed,
                "create": list(result.create),
                "drop": list(result.drop),
                "not_possible": [],
                "complete": result.complete,
            },
            "why": (
                "Every column list here comes out sorted by name even though the document lists "
                "them reversed, and the two lists that matter are the CREATE TABLE and the view's "
                "SELECT - separate statements, so removing either sort changes a different string "
                "and neither can hide behind the other. Column *types* stay attached to their "
                "columns, which is the part a naive 'sort the values too' would get wrong."
            ),
        }
    ]
    _write("009-columns-out-of-order-in-the-document", model, raw, cases)


def _ten() -> None:
    """One model with every type both engines map, and both layouts in one map.

    Two jobs. As a schema vector it pins the DDL for the whole neutral vocabulary minus the two
    types ClickHouse deliberately has no column for. And as a fixture it is what the TypeScript
    library's engine-agreement test round-trips through: the same value written through both
    adapters has to come back identical in content **and** in JavaScript type, and the layouts it
    writes against have to be the ones a planner would issue rather than ones a test typed out.

    `bytes` and `json` are absent on purpose. ClickHouse has no column for them in this library, so
    `default_layout` refuses that dialect for a group containing one - which is the mechanism that
    stops a planner placing such a group there, and it is checked by its own test rather than here.
    """
    sde.clear_registry()
    model = model_from_neutral(
        {
            "entities": [
                {
                    "name": "Sample",
                    "fields": [
                        {"name": "id", "type": "uuid"},
                        {"name": "label", "type": "string"},
                        {"name": "small", "type": "int32"},
                        {"name": "big", "type": "int64"},
                        {"name": "approx", "type": "float64"},
                        {"name": "narrow", "type": "float32"},
                        {"name": "money", "type": "decimal(12,2)"},
                        {"name": "flag", "type": "bool"},
                        {"name": "at", "type": "timestamptz"},
                        {"name": "naive", "type": "timestamp"},
                        {"name": "day", "type": "date"},
                    ],
                    "key": ["id"],
                }
            ],
            "relations": [],
            "atomic": [],
        }
    )
    group = "Sample"
    members = next(g for g in sde.colocation_groups(model) if g.name == group)
    pg = sde.default_layout(model, members)
    ch = sde.default_layout(model, members, dialect="clickhouse")
    raw = _map(model, {group: {"id": "Sample@pg", "engine": "pg-main", "layout": _layout_doc(pg)}})
    raw["groups"][group]["derived"] = [
        {"id": "Sample@ch", "engine": "ch-1", "layout": _layout_doc(ch), "lag_budget_ms": 30000}
    ]
    cases = [
        {
            "materialization": "Sample@pg",
            "dialect": "postgres",
            "fixed": False,
            "statements": _statements(pg, model, group, "postgres"),
            "why": (
                "Every type this library maps for PostgreSQL, in one statement, so a change to the "
                "type table is a change to this file. The pair with the ClickHouse case below is "
                "the useful part: two columns of the same neutral type, spelled by two engines, and "
                "an adapter has to give a caller the same value back from either."
            ),
        },
        {
            "materialization": "Sample@ch",
            "dialect": "clickhouse",
            "fixed": False,
            "statements": _statements(ch, model, group, "clickhouse"),
            "why": (
                "The same model in the other dialect. `DateTime64(3, 'UTC')` against "
                "`timestamptz` is the pair that has already cost this project a measured two-hour "
                "divergence, and `Decimal(12, 2)` against `numeric(12,2)` is the one where a "
                "float conversion would come back changed with no error anywhere. Both are "
                "round-tripped through real servers by the engine-agreement tests, which is what "
                "makes this vector a fixture as well as an expectation."
            ),
        },
    ]
    _write("010-every-type-both-engines-map", model, raw, cases)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--i-am-changing-the-contract", action="store_true")
    args = parser.parse_args()
    if not args.i_am_changing_the_contract:
        print(__doc__)
        print("Refusing to run without --i-am-changing-the-contract.")
        return 1
    VECTORS.mkdir(parents=True, exist_ok=True)
    print("schema vectors:")
    _one()
    _two()
    _three()
    _four()
    _five()
    _six()
    _seven()
    _eight()
    _nine()
    _ten()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
