"""Generate the ``signature/`` vectors, with every signature produced and checked by openssl.

These vectors exist because accepting **a set** of public keys is what makes rotating our signing
key possible without breaking a client, and an acceptance rule that holds in one runtime and not
another is one map with two meanings - the divergence class this whole suite exists for.

Two things here are deliberate.

**No private key is ever written into the repository.** Each key pair is generated in a temporary
directory and discarded; what is committed is the raw 32-byte public key and a signature over the
map. Regenerating means new key pairs and new signatures, which is fine: a signature is not one of
the golden artefacts that has to stay byte-stable. The model IR digests are, and nothing here
touches them.

**The signatures come from openssl, not from this library.** Same reason as the hashing vectors:
generated by the implementation they verify, they would freeze a bug in it. The honest limitation is
that the *payload* - the canonical encoding of the map without its signature block - does come from
this library, because openssl cannot compute our canonical form. That part is pinned separately and
harder, by ``model/001-single-entity``, which was typed out by a person from the document.

    python conformance/tools/signature_vectors.py --i-am-changing-the-contract
"""

from __future__ import annotations

import argparse
import base64
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
VECTORS = ROOT / "conformance" / "vectors" / "signature"
BASE = ROOT / "conformance" / "vectors" / "errors" / "014-a-signed-map-with-no-key-to-check-it"

# The 12-byte SubjectPublicKeyInfo prefix an Ed25519 public key carries in DER. Restated rather
# than parsed: the whole point of asking openssl is that this script shares no code with the
# libraries, and a DER parser here would be a third implementation of the same 12 bytes.
DER_PREFIX = bytes.fromhex("302a300506032b6570032100")


def openssl(*args: str, stdin: bytes | None = None) -> bytes:
    result = subprocess.run(
        ["openssl", *args], input=stdin, capture_output=True, check=False
    )
    if result.returncode != 0:
        raise SystemExit(f"openssl {' '.join(args)} failed: {result.stderr.decode()}")
    return result.stdout


class KeyPair:
    """One throwaway Ed25519 key pair, living in a temporary directory."""

    def __init__(self, home: Path, name: str) -> None:
        self.name = name
        self.private = home / f"{name}.pem"
        openssl("genpkey", "-algorithm", "ed25519", "-out", str(self.private))
        der = openssl("pkey", "-in", str(self.private), "-pubout", "-outform", "DER")
        if not der.startswith(DER_PREFIX) or len(der) != len(DER_PREFIX) + 32:
            raise SystemExit(f"unexpected DER shape for {name}: {der.hex()}")
        self.public = der[len(DER_PREFIX) :]

    def sign(self, payload: bytes, home: Path) -> bytes:
        message = home / f"{self.name}.msg"
        signature = home / f"{self.name}.sig"
        message.write_bytes(payload)
        openssl(
            "pkeyutl", "-sign", "-rawin", "-inkey", str(self.private),
            "-in", str(message), "-out", str(signature),
        )
        # Checked before anything is written. A vector whose signature does not verify would fail
        # in every language at once and read as a library bug in all of them.
        public_pem = home / f"{self.name}.pub.pem"
        public_pem.write_bytes(
            openssl("pkey", "-in", str(self.private), "-pubout")
        )
        out = openssl(
            "pkeyutl", "-verify", "-rawin", "-pubin", "-inkey", str(public_pem),
            "-in", str(message), "-sigfile", str(signature),
        )
        if b"Verified Successfully" not in out:
            raise SystemExit(f"openssl would not verify its own signature for {self.name}")
        return signature.read_bytes()


def payload_of(document: dict[str, Any]) -> bytes:
    """The canonical bytes a signature covers: everything but the signature block.

    Imported here rather than restated, and this is the one part openssl cannot replace.
    """
    sys.path.insert(0, str(ROOT / "python" / "src"))
    from sde.canonical import canonical_bytes

    return canonical_bytes({k: v for k, v in document.items() if k != "signature"})


def write(case: str, *, model: Any, document: Any, keys: dict[str, str], expected: Any) -> None:
    target = VECTORS / case
    target.mkdir(parents=True, exist_ok=True)
    (target / "model.json").write_text(json.dumps(model, indent=2, sort_keys=True) + "\n")
    (target / "map.json").write_text(json.dumps(document, indent=2, sort_keys=True) + "\n")
    (target / "keys.json").write_text(json.dumps(keys, indent=2, sort_keys=True) + "\n")
    (target / "expected.json").write_text(json.dumps(expected, indent=2, sort_keys=True) + "\n")
    print(f"  wrote {case}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--i-am-changing-the-contract", action="store_true", required=True)
    parser.parse_args()

    model = json.loads((BASE / "model.json").read_text())
    document = json.loads((BASE / "map.json").read_text())
    document.pop("signature", None)
    payload = payload_of(document)

    if VECTORS.exists():
        shutil.rmtree(VECTORS)

    with tempfile.TemporaryDirectory() as home_name:
        home = Path(home_name)
        k1 = KeyPair(home, "k1")
        k2 = KeyPair(home, "k2")
        stranger = KeyPair(home, "stranger")

        b64 = lambda raw: base64.b64encode(raw).decode()  # noqa: E731

        signed_by_k1 = {
            **document,
            "signature": {"alg": "ed25519", "key_id": "k1", "value": b64(k1.sign(payload, home))},
        }
        signed_by_k2 = {
            **document,
            "signature": {"alg": "ed25519", "key_id": "k2", "value": b64(k2.sign(payload, home))},
        }
        signed_by_stranger = {
            **document,
            "signature": {
                "alg": "ed25519",
                "key_id": "k1",
                "value": b64(stranger.sign(payload, home)),
            },
        }
        # Same signature as signed_by_k2, with the hint pointing at the wrong key. The point of the
        # vector below: key_id is outside the signed payload, so anybody can edit it.
        misleading = {
            **signed_by_k2,
            "signature": {**signed_by_k2["signature"], "key_id": "k1"},
        }

        write(
            "001-one-unnamed-key-verifies",
            model=model,
            document=signed_by_k1,
            keys={"": b64(k1.public)},
            expected={
                "verified_with": None,
                "why": "the ordinary case: one key, no rotation in progress. The empty name is how "
                "a caller passing a bare key is represented, and the library reports no name back "
                "because it was given none. `signed` is what tells this apart from an unsigned "
                "map; one field meaning two things is how a value ends up standing for four.",
            },
        )
        write(
            "002-the-second-key-of-a-set-verifies",
            model=model,
            document=signed_by_k2,
            keys={"k1": b64(k1.public), "k2": b64(k2.public)},
            expected={
                "verified_with": "k2",
                "why": "the overlap window during a rotation, which is the whole point of "
                "accepting a set: we sign with the new key while the client still has both, and "
                "nothing about their deployment has to change at the same moment ours does. The "
                "id that verified is reported because adding a key is reversible and removing one "
                "is not - a client cannot know when the old key is safe to drop otherwise.",
            },
        )
        write(
            "003-the-key-id-is-only-a-hint",
            model=model,
            document=misleading,
            keys={"k1": b64(k1.public), "k2": b64(k2.public)},
            expected={
                "verified_with": "k2",
                "why": "this map is signed with k2 and says k1. The signature block is excluded "
                "from the signed payload in its entirety, so key_id is not covered by the "
                "signature and anybody can edit it - a library that treated it as authoritative "
                "would be refusing a perfectly good map on an attacker's annotation. It orders "
                "the attempts and nothing else, so being wrong about it costs one failed "
                "verification and reaches the same answer.",
            },
        )
        write(
            "007-adding-a-key-does-not-invalidate-what-the-old-one-signed",
            model=model,
            document=signed_by_k1,
            keys={"k1": b64(k1.public), "k2": b64(k2.public)},
            expected={
                "verified_with": "k1",
                "why": "the claim requirement 14.2 can actually keep: a rotation that does not "
                "break the client. The client adds our new key and every map already in their "
                "hands still verifies - so the two sides do not have to change in the same "
                "second, which matters because our signing key is never overwritten and theirs "
                "is a configuration change in their deployment. This is the half that makes "
                "adding safe; removing is the irreversible half and is theirs to time.",
            },
        )
        write(
            "004-no-configured-key-verifies",
            model=model,
            document=signed_by_stranger,
            keys={"k1": b64(k1.public), "k2": b64(k2.public)},
            expected={
                "error": "MapError",
                "match": "does not verify against any of the 2 key",
                "why": "signed with a key the client does not have. The refusal has to name how "
                "many keys were tried and which one the map asked for, because during a rotation "
                "this is the message that says whether the new key is missing from the client's "
                "configuration or the map came from somewhere else entirely.",
            },
        )
        write(
            "005-a-key-of-the-wrong-length-is-refused",
            model=model,
            document=signed_by_k1,
            keys={"k1": b64(k1.public[:31])},
            expected={
                "error": "MapError",
                "match": "31 bytes and an Ed25519 public key is 32",
                "why": "the client's configuration, not the map. Refused before verification is "
                "attempted, because a key pasted a byte short would otherwise look identical to a "
                "map that does not verify - and the two have completely different fixes. Before "
                "this it was a bare ValueError out of the parser on the application's start path.",
            },
        )
        write(
            "006-an-empty-key-set-is-refused",
            model=model,
            document=signed_by_k1,
            keys={},
            expected={
                "error": "MapError",
                "match": "empty set of public keys",
                "why": "an empty set is not the no-account mode - a map with no signature is. It "
                "is a configuration that can verify nothing, and saying so is better than a "
                "refusal blaming the map.",
            },
        )

    print("done; the private keys were in a temporary directory and are gone")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
