/// The read's SQL against the reference's own: every case below is a read the reference planned,
/// with the statements `sde.query.read_sql` and `summary_sql` rendered for it in both dialects - or
/// the refusal - and each value they bound, in binding order. The cases were picked from a random
/// corpus so that between them they cover every way the SQL varies; the comparison on the corpus
/// itself, 40,000 reads at a time, runs outside the suite.

#include <exception>
#include <string>
#include <string_view>
#include <typeinfo>
#include <vector>

#include <gtest/gtest.h>

#include "python_compat.hpp"
#include "sde/canonical.hpp"
#include "sde/errors.hpp"
#include "sde/json.hpp"
#include "sde/query.hpp"

namespace {

// Generated by the reference; each line is the read's columns, key and options, and `want`.
const std::vector<std::string_view> kCases = {
    R"json({"columns":[["id","json"]],"key":[],"options":{"paginate":true,"descending":true,"limit":1},"want":{"refused":"QueryRefused: a paginated read requires an entity key"}})json",
    R"json({"columns":[["at","uuid"]],"key":[],"options":{"paginate":false,"descending":false,"limit":2},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\"","params":[]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL","params":[]}]}})json",
    R"json({"columns":[["ref","decimal(76,0)"]],"key":["ref"],"options":{"paginate":true,"descending":false,"limit":1,"where":{"ref":"12345.67"}},"want":{"rendered":[{"dialect":"postgres","kind":"read","column":null,"refused":"QueryRefused: decimal comparison requires more than 76 digits"},{"dialect":"clickhouse","kind":"read","column":null,"refused":"QueryRefused: decimal comparison requires more than 76 digits"}]}})json",
    R"json({"columns":[["at","date"]],"key":["at"],"options":{"paginate":true,"descending":true,"limit":1},"want":{"rendered":[{"dialect":"postgres","kind":"read","column":null,"sql":"SELECT \"at\" FROM \"t\"\"able\" ORDER BY \"at\" DESC NULLS LAST LIMIT $1","params":[["int","2"]]},{"dialect":"clickhouse","kind":"read","column":null,"sql":"SELECT `at` FROM `t\"able` FINAL ORDER BY `at` DESC NULLS LAST LIMIT {p1}","params":[["int","2"]]}]}})json",
    R"json({"columns":[["day","timestamptz"]],"key":[],"options":{"paginate":false,"descending":false,"limit":2,"where":{"day":null}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\" WHERE \"day\" IS NULL","params":[]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL WHERE `day` IS NULL","params":[]}]}})json",
    R"json({"columns":[["at","timestamp"]],"key":["at"],"options":{"paginate":true,"descending":false,"limit":100},"want":{"rendered":[{"dialect":"postgres","kind":"read","column":null,"sql":"SELECT \"at\" FROM \"t\"\"able\" ORDER BY \"at\" ASC NULLS LAST LIMIT $1","params":[["int","101"]]},{"dialect":"clickhouse","kind":"read","column":null,"sql":"SELECT toTimeZone(`at`, 'UTC') AS `at` FROM `t\"able` FINAL ORDER BY `at` ASC NULLS LAST LIMIT {p1}","params":[["int","101"]]}]}})json",
    R"json({"columns":[["name","string"]],"key":["name"],"options":{"paginate":true,"descending":true,"limit":1000},"want":{"rendered":[{"dialect":"postgres","kind":"read","column":null,"sql":"SELECT \"name\" FROM \"t\"\"able\" ORDER BY (\"name\" COLLATE \"C\") DESC NULLS LAST LIMIT $1","params":[["int","1001"]]},{"dialect":"clickhouse","kind":"read","column":null,"sql":"SELECT `name` FROM `t\"able` FINAL ORDER BY `name` DESC NULLS LAST LIMIT {p1}","params":[["int","1001"]]}]}})json",
    R"json({"columns":[["ref","bool"]],"key":["ref"],"options":{"paginate":false,"descending":false,"limit":100,"where":{"ref":true}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\" WHERE \"ref\" = $1","params":[["bool","true"]]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL WHERE `ref` = {p1}","params":[["bool","true"]]}]}})json",
    R"json({"columns":[["ref","date"]],"key":[],"options":{"paginate":false,"descending":false,"limit":1000,"where":{"ref":"9999-12-31"}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\" WHERE \"ref\" = $1","params":[["date","9999-12-31"]]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL WHERE `ref` = {p1}","params":[["date","9999-12-31"]]}]}})json",
    R"json({"columns":[["x y","date"]],"key":["x y"],"options":{"paginate":true,"descending":false,"limit":1,"where":{"x y":null}},"want":{"rendered":[{"dialect":"postgres","kind":"read","column":null,"sql":"SELECT \"x y\" FROM \"t\"\"able\" WHERE \"x y\" IS NULL ORDER BY \"x y\" ASC NULLS LAST LIMIT $1","params":[["int","2"]]},{"dialect":"clickhouse","kind":"read","column":null,"sql":"SELECT `x y` FROM `t\"able` FINAL WHERE `x y` IS NULL ORDER BY `x y` ASC NULLS LAST LIMIT {p1}","params":[["int","2"]]}]}})json",
    R"json({"columns":[["name","string"]],"key":["name"],"options":{"paginate":true,"descending":true,"limit":2,"after":{"name":null}},"want":{"rendered":[{"dialect":"postgres","kind":"read","column":null,"sql":"SELECT \"name\" FROM \"t\"\"able\" WHERE FALSE ORDER BY (\"name\" COLLATE \"C\") DESC NULLS LAST LIMIT $1","params":[["int","3"]]},{"dialect":"clickhouse","kind":"read","column":null,"sql":"SELECT `name` FROM `t\"able` FINAL WHERE FALSE ORDER BY `name` DESC NULLS LAST LIMIT {p1}","params":[["int","3"]]}]}})json",
    R"json({"columns":[["at","float32"]],"key":[],"options":{"paginate":false,"descending":true,"limit":100,"where":{"at":0.1}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\" WHERE CAST(\"at\" AS double precision) = $1","params":[["float","0.1"]]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL WHERE toFloat64(`at`) = {p1}","params":[["float","0.1"]]}]}})json",
    R"json({"columns":[["id","timestamp"]],"key":[],"options":{"paginate":false,"descending":true,"limit":1000,"where":{"id":"2026-10-07T12:00:00"}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\" WHERE \"id\" = $1","params":[["timestamp","2026-10-07T12:00:00.000000"]]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL WHERE `id` = {p1}","params":[["timestamp","2026-10-07T12:00:00.000000"]]}]}})json",
    R"json({"columns":[["at","timestamptz"]],"key":["at"],"options":{"paginate":false,"descending":false,"limit":100,"where":{"at":"2026-10-07T12:00:00Z"}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\" WHERE \"at\" = $1","params":[["timestamptz","2026-10-07T12:00:00.000000+00:00"]]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL WHERE `at` = {p1}","params":[["timestamptz","2026-10-07T12:00:00.000000+00:00"]]}]}})json",
    R"json({"columns":[["at","uuid"]],"key":[],"options":{"paginate":false,"descending":true,"limit":1000,"where":{"at":"FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF"}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\" WHERE \"at\" = $1","params":[["uuid","ffffffff-ffff-ffff-ffff-ffffffffffff"]]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL WHERE `at` = toUUID({p1})","params":[["str","ffffffff-ffff-ffff-ffff-ffffffffffff"]]}]}})json",
    R"json({"columns":[["day","float64"]],"key":[],"options":{"paginate":false,"descending":false,"limit":1,"bounds":{"field":"day","low":0.1,"high":null}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\" WHERE (CAST(\"day\" AS double precision) <> 'NaN'::double precision AND CAST(\"day\" AS double precision) >= $1)","params":[["float","0.1"]]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL WHERE (NOT isNaN(toFloat64(`day`)) AND toFloat64(`day`) >= {p1})","params":[["float","0.1"]]}]}})json",
    R"json({"columns":[["x y","decimal(60,30)"]],"key":[],"options":{"paginate":false,"descending":false,"limit":1000},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\"","params":[]},{"dialect":"postgres","kind":"summary","column":"x y","refused":"QueryRefused: summaries require int32, int64 or decimal precision up to 56"},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL","params":[]},{"dialect":"clickhouse","kind":"summary","column":"x y","refused":"QueryRefused: summaries require int32, int64 or decimal precision up to 56"}]}})json",
    R"json({"columns":[["day","decimal(12,2)"]],"key":["day"],"options":{"paginate":true,"descending":true,"limit":1,"where":{"day":"1E+3"}},"want":{"rendered":[{"dialect":"postgres","kind":"read","column":null,"sql":"SELECT CAST(\"day\" AS text) AS \"day\" FROM \"t\"\"able\" WHERE CAST(\"day\" AS numeric(76,2)) = CAST($1 AS numeric(76,2)) ORDER BY \"day\" DESC NULLS LAST LIMIT $2","params":[["str","1000"],["int","2"]]},{"dialect":"clickhouse","kind":"read","column":null,"sql":"SELECT toString(`day`) AS `day` FROM `t\"able` FINAL WHERE CAST(`day` AS Nullable(Decimal(76,2))) = CAST({p1} AS Nullable(Decimal(76,2))) ORDER BY `day` DESC NULLS LAST LIMIT {p2}","params":[["str","1000"],["int","2"]]}]}})json",
    R"json({"columns":[["x y","decimal(76,0)"]],"key":["x y"],"options":{"paginate":false,"descending":true,"limit":100,"where":{"x y":"12345.67"}},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"refused":"QueryRefused: decimal comparison requires more than 76 digits"},{"dialect":"postgres","kind":"summary","column":"x y","refused":"QueryRefused: summaries require int32, int64 or decimal precision up to 56"},{"dialect":"clickhouse","kind":"count","column":null,"refused":"QueryRefused: decimal comparison requires more than 76 digits"},{"dialect":"clickhouse","kind":"summary","column":"x y","refused":"QueryRefused: summaries require int32, int64 or decimal precision up to 56"}]}})json",
    R"json({"columns":[["id","int64"]],"key":[],"options":{"paginate":false,"descending":true,"limit":1},"want":{"rendered":[{"dialect":"postgres","kind":"count","column":null,"sql":"SELECT CAST(count(*) AS text) AS sde_count FROM \"t\"\"able\"","params":[]},{"dialect":"postgres","kind":"summary","column":"id","sql":"SELECT CAST(count(*) AS text) AS sde_count, CAST(count(\"id\") AS text) AS sde_present, CAST(min(\"id\") AS text) AS sde_min, CAST(max(\"id\") AS text) AS sde_max, CAST(sum(CAST(\"id\" AS numeric(76,0))) AS text) AS sde_total FROM \"t\"\"able\"","params":[]},{"dialect":"clickhouse","kind":"count","column":null,"sql":"SELECT toString(count()) AS sde_count FROM `t\"able` FINAL","params":[]},{"dialect":"clickhouse","kind":"summary","column":"id","sql":"SELECT toString(count(*)) AS sde_count, toString(count(`id`)) AS sde_present, toString(min(`id`)) AS sde_min, toString(max(`id`)) AS sde_max, toString(sum(CAST(`id` AS Nullable(Decimal(76,0))))) AS sde_total FROM `t\"able` FINAL","params":[]}]}})json",
};

sde::Value value_of(const sde::Json& json) {
  switch (json.kind()) {
    case sde::Json::Kind::null:
      return sde::Null{};
    case sde::Json::Kind::boolean:
      return json.as_bool();
    case sde::Json::Kind::number:
      if (json.as_number().integer) return *json.to_int64();
      return *json.to_double();
    case sde::Json::Kind::string:
      return json.as_string();
    default:
      throw std::logic_error("a case's values are scalars");
  }
}

sde::Row row_of(const sde::Json& json) {
  sde::Row row;
  for (const auto& [name, value] : json.as_object()) row[name] = value_of(value);
  return row;
}

/// A bound value as the reference's generator writes it: a tag and the text both libraries write.
sde::Json tagged(const sde::Value& value) {
  sde::Json out = sde::Json::array();
  const auto put = [&](const char* tag, std::string text) {
    out.as_array().push_back(tag);
    out.as_array().push_back(std::move(text));
  };
  if (const auto* flag = std::get_if<bool>(&value)) {
    put("bool", *flag ? "true" : "false");
  } else if (const auto* integer = std::get_if<std::int64_t>(&value)) {
    put("int", std::to_string(*integer));
  } else if (const auto* number = std::get_if<double>(&value)) {
    put("float", sde::detail::python_float_repr(*number));
  } else if (const auto* text = std::get_if<std::string>(&value)) {
    put("str", *text);
  } else if (const auto* naive = std::get_if<sde::Timestamp>(&value)) {
    put("timestamp", naive->to_string());
  } else if (const auto* instant = std::get_if<sde::TimestampTz>(&value)) {
    std::string written = instant->to_string();
    written.replace(written.size() - 1, 1, "+00:00");  // UTC as Python's isoformat writes it
    put("timestamptz", written);
  } else if (const auto* date = std::get_if<sde::Date>(&value)) {
    put("date", date->to_string());
  } else if (const auto* uuid = std::get_if<sde::Uuid>(&value)) {
    put("uuid", uuid->to_string());
  } else {
    put("?", std::string(sde::value_kind(value)));
  }
  return out;
}

std::string refused(const std::exception& error) {
  const std::string name = typeid(error) == typeid(sde::QueryRefused) ? "QueryRefused" : "other";
  return name + ": " + error.what();
}

sde::Json answer(const sde::Json& item) {
  std::vector<sde::ReadColumn> columns;
  for (const sde::Json& column : item.find("columns")->as_array()) {
    columns.push_back({column.as_array()[0].as_string(), column.as_array()[1].as_string()});
  }
  std::vector<std::string> key;
  for (const sde::Json& name : item.find("key")->as_array()) key.push_back(name.as_string());
  const sde::Json& given = *item.find("options");
  sde::ReadOptions options;
  options.paginate = given.find("paginate")->as_bool();
  options.descending = given.find("descending")->as_bool();
  options.limit = *given.find("limit")->to_int64();
  if (const sde::Json* where = given.find("where")) options.where = row_of(*where);
  if (const sde::Json* bounds = given.find("bounds")) {
    options.bounds = sde::Range{bounds->find("field")->as_string(), value_of(*bounds->find("low")),
                                value_of(*bounds->find("high"))};
  }
  if (const sde::Json* order_by = given.find("order_by")) options.order_by = order_by->as_string();
  if (const sde::Json* after = given.find("after")) options.after = row_of(*after);
  sde::Json out = sde::Json::object();
  sde::ReadPlan plan;
  try {
    plan = sde::plan_read(columns, key, options);
  } catch (const std::exception& error) {
    out.set("refused", refused(error));
    return out;
  }
  sde::Json rendered = sde::Json::array();
  for (const char* name : {"postgres", "clickhouse"}) {
    const std::string dialect = name;
    std::vector<std::pair<std::string, const sde::ReadColumn*>> jobs;
    if (options.paginate) {
      jobs.emplace_back("read", nullptr);
    } else {
      jobs.emplace_back("count", nullptr);
      for (const sde::ReadColumn& column : columns) {
        if (column.type == "int32" || column.type == "int64" ||
            column.type.starts_with("decimal(")) {
          jobs.emplace_back("summary", &column);
        }
      }
    }
    for (const auto& [kind, column] : jobs) {
      sde::Json params = sde::Json::array();
      const sde::Parameter parameter = [&](const sde::Value& value) {
        params.as_array().push_back(tagged(value));
        const std::string n = std::to_string(params.as_array().size());
        return dialect == "postgres" ? "$" + n : "{p" + n + "}";
      };
      sde::Json entry = sde::Json::object();
      entry.set("dialect", dialect);
      entry.set("kind", kind);
      entry.set("column", column != nullptr ? sde::Json(column->name) : sde::Json(nullptr));
      try {
        entry.set("sql", kind == "summary"
                             ? sde::summary_sql("t\"able", plan, *column, dialect, parameter)
                             : sde::read_sql("t\"able", plan, dialect, parameter, kind == "count"));
        entry.set("params", params);
      } catch (const std::exception& error) {
        entry.set("refused", refused(error));
      }
      rendered.as_array().push_back(std::move(entry));
    }
  }
  out.set("rendered", rendered);
  return out;
}

TEST(ReadSql, RendersAndBindsWhatTheReferenceDoes) {
  ASSERT_FALSE(kCases.empty());
  for (const std::string_view line : kCases) {
    const sde::Json item = sde::parse_json(line);
    const sde::Json got = answer(item);
    EXPECT_EQ(got, *item.find("want")) << sde::canonical_bytes(*item.find("options")) << "\n"
                                       << "  this:      " << sde::canonical_bytes(got);
  }
}

TEST(ReadSql, BindsEachOccurrenceOfAPositionInStatementOrder) {
  // A position of two columns writes the first one twice: once on its own, once as the prefix of
  // the second. Positional placeholders need each occurrence bound where it stands.
  const std::vector<sde::ReadColumn> columns = {{"a", "int64"}, {"b", "string"}};
  sde::ReadOptions options;
  options.after = sde::Row{{"a", std::int64_t{7}}, {"b", "x"}};
  const sde::ReadPlan plan = sde::plan_read(columns, {"a", "b"}, options);
  std::vector<std::string> bound;
  const std::string sql = sde::read_sql("t", plan, "postgres", [&](const sde::Value& value) {
    bound.push_back(std::string(sde::value_kind(value)));
    return "$" + std::to_string(bound.size());
  });
  // The reference's own text for this plan.
  EXPECT_EQ(sql,
            R"(SELECT "a", "b" FROM "t" WHERE ((("a" IS NULL OR "a" > $1)) OR ("a" = $2 AND )"
            R"((("b" COLLATE "C") IS NULL OR ("b" COLLATE "C") > $3))) ORDER BY "a" ASC NULLS )"
            R"(LAST, ("b" COLLATE "C") ASC NULLS LAST LIMIT $4)");
  EXPECT_EQ(bound, (std::vector<std::string>{"int64", "int64", "string", "int64"}));
}

}  // namespace
