/**
 * The two adapters, against real servers.
 *
 * Requirement 17.5 asks a Tier 2 implementation for drivers to PostgreSQL and ClickHouse **in its
 * own language, with tests of transaction semantics** - and says where the real cost of the
 * multi-language decision lies: four languages times two engines is eight integrations. This file
 * is two of the eight.
 *
 * Skipped rather than faked when the servers are absent. A fake agrees with whatever this library
 * believes about types and quoting, which is precisely the belief under test - and CI has a step
 * that fails if these skipped, because a skipped integration test is indistinguishable from a
 * passing one in a summary line.
 *
 * The layouts come from `conformance/vectors/schema/010`, which is generated by the reference
 * implementation's planner. That matters more than it looks: a layout typed out in a test is a
 * layout that agrees with this test, and the value of the agreement check below is that the two
 * column *spellings* are the ones a client would actually be issued.
 *
 * The most important test here is the last one. Two engines, one value, and the assertion that it
 * comes back identical in content **and** in JavaScript type - which is where the reference
 * implementation found two divergences living: a naive datetime two hours apart, and one column
 * that could not be compared at all because one driver returned an aware value and the other a
 * naive one.
 */

import { randomUUID } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { afterAll, beforeAll, 
describe, expect, it } from 'vitest'

import type { LogicalModel, PlacementMap, Row } from '../src/index.js'
import { EngineError, loadMap, Session } from '../src/index.js'
import { ClickHouseEngine } from '../src/engines/clickhouse.js'
import { PostgresEngine } from '../src/engines/postgres.js'
import { modelFromNeutral } from '../src/testing/loader.js'

const PG_DSN = process.env['SDE_POSTGRES_DSN']
const CH_DSN = process.env['SDE_CLICKHOUSE_DSN']

const VECTOR = join(
  __dirname,
  '..',
  '..',
  'conformance',
  'vectors',
  'schema',
  '010-every-type-both-engines-map',
)

function fixture(): { model: LogicalModel; map: PlacementMap } {
  const model = modelFromNeutral(
    JSON.parse(readFileSync(join(VECTOR, 'model.json'), 'utf8')) as Record<string, unknown>,
  )
  const map = loadMap(
    JSON.parse(readFileSync(join(VECTOR, 'map.json'), 'utf8')) as Record<string, unknown>,
    { model },
  )
  return { model, map }
}

const KEYS = { Sample: ['id'] } as const

/** A row using every type the fixture declares, with values chosen to be awkward. */
function sample(id: string): Row {
  return {
    id,
    label: 'zażółć gęślą jaźń',
    small: -2_147_483_648,
    big: 9_007_199_254_740_993n, // 2^53 + 1: the first integer a `number` cannot hold exactly
    approx: 0.1,
    narrow: 0.5,
    money: '12.34',
    flag: true,
    at: new Date('2026-08-27T12:00:00.000Z'),
    naive: new Date('2026-08-27T12:00:00.000Z'),
    day: '2026-08-27',
  }
}

/**
 * A marker whose purpose is its **skip**.
 *
 * Vitest reports a file whose every suite was skipped as "no tests" and *fails* it - which does two
 * unwanted things: it makes the suite unrunnable for anybody without servers, and it gives CI's
 * did-not-skip guard nothing to look for, because "no tests" does not contain the word "skipped".
 * One test at the top level fixes both. Measured rather than assumed: without the DSNs the summary
 * read `Test Files 1 failed` and `Tests no tests`, and the guard reported everything as fine.
 */
it.skipIf(!PG_DSN || !CH_DSN)('has both engines configured', () => {
  expect(PG_DSN, 'set SDE_POSTGRES_DSN to run this file').toBeTruthy()
  expect(CH_DSN, 'set SDE_CLICKHOUSE_DSN to run this file').toBeTruthy()
})

describe.skipIf(!PG_DSN)('the PostgreSQL adapter', () => {
  const { model, map } = fixture()
  const layout = map.groups['Sample']?.source.layout
  // Constructed in the hook rather than here, and that is not style. `describe.skipIf` still
  // **runs its callback** - it has to, to register the tests it then skips - so an engine built at
  // this level parses a DSN that is `undefined` and takes the whole file down at collection with a
  // refusal that reads like a real one. Measured: without the variables the file failed and
  // reported "no tests", which is also what defeats CI's did-not-skip guard.
  let engine: PostgresEngine

  beforeAll(async () => {
    engine = new PostgresEngine(PG_DSN as string)
    await engine.connect()
  // **Dropped before created, which the Python side has always done and this file never did.**
  // These suites share one database with the Python live tests, and `CREATE TABLE IF NOT EXISTS`
  // keeps whatever is already there - so whichever language ran first decided the shape and the
  // other one's create path was never exercised. Invisible until the adapters started verifying
  // column *types* on 7 September 2026, at which point a `DateTime64(3, 'UTC')` left by an older
  // run was refused here. The refusal was right; the fixture was wrong.
    await dropPostgres(Object.values(layout!.tables))
    await engine.ensureSchema(layout!, { keys: KEYS })
  })
  afterAll(async () => {
    await engine.close()
  })

  it('round-trips every type the layout declares', async () => {
    const id = randomUUID()
    const row = sample(id)
    await engine.insert('sample', row)
    const back = await engine.get('sample', { id })
    expect(back).not.toBeNull()
    // int64 as a bigint, because 2^53 + 1 does not survive a number.
    expect(back?.['big']).toBe(9_007_199_254_740_993n)
    // decimal as a string, because there is no exact decimal here and a float comes back changed.
    expect(back?.['money']).toBe('12.34')
    // a calendar date has no zone, so it stays a calendar date.
    expect(back?.['day']).toBe('2026-08-27')
    expect((back?.['at'] as Date).toISOString()).toBe('2026-08-27T12:00:00.000Z')
    expect(back?.['label']).toBe('zażółć gęślą jaźń')
    expect(back?.['flag']).toBe(true)
    expect(back?.['small']).toBe(-2_147_483_648)
  })

  it('refuses a table that already exists with a different shape', async () => {
    // `CREATE TABLE IF NOT EXISTS` keeps whatever is there, so a leftover from something else is
    // accepted silently and the first insert fails with an error naming a column and not the cause.
    await engine.insert('sample', sample(randomUUID()))
    const thin = {
      tables: { Sample: 'sample_thin' },
      columns: { Sample: { id: 'uuid' } },
      indexes: [],
      partitionBy: {},
    }
    await engine.ensureSchema(thin, { keys: KEYS })
    const wide = {
      ...thin,
      columns: { Sample: { id: 'uuid', missing_column: 'text' } },
    }
    await expect(engine.ensureSchema(wide, { keys: KEYS })).rejects.toThrow(
      'already existed with a different shape',
    )
  })

  it('commits a transaction and rolls one back', async () => {
    const committed = randomUUID()
    await engine.transaction(async () => {
      await engine.insert('sample', sample(committed))
    })
    expect(await engine.get('sample', { id: committed })).not.toBeNull()

    const abandoned = randomUUID()
    await expect(
      engine.transaction(async () => {
        await engine.insert('sample', sample(abandoned))
        throw new Error('the application failed here')
      }),
    ).rejects.toThrow('the application failed here')
    // The row never existed, which is the whole point: one engine, one transaction, its semantics.
    expect(await engine.get('sample', { id: abandoned })).toBeNull()
  })

  it('enforces the key, which is the divergence ClickHouse cannot remove', async () => {
    const id = randomUUID()
    await engine.insert('sample', sample(id))
    await expect(engine.insert('sample', sample(id))).rejects.toThrow(EngineError)
  })

  it('scans in key order, resumes by position and copies idempotently', async () => {
    // A table of its own per run. The first version reused one name and passed once: the second run
    // found the previous run's five rows and the assertion about the first page was about somebody
    // else's data. A test whose fixture survives the run is a test that reports on a different
    // state than the one it set up.
    const table = `sample_scan_${randomUUID().replace(/-/g, '')}`
    const layoutForScan = {
      tables: { Sample: table },
      columns: layout?.columns ?? {},
      indexes: [],
      partitionBy: {},
    }
    await engine.ensureSchema(layoutForScan, { keys: KEYS })
    const ids = [...Array(5)].map(() => randomUUID()).sort()
    for (const id of ids) await engine.insert(table, sample(id))

    const first = await engine.keyRange(table, ['id'], { limit: 2 })
    expect(first.map((row) => row['id'])).toEqual(ids.slice(0, 2))
    const next = await engine.keyRange(table, ['id'], { after: [ids[1]], limit: 2 })
    expect(next.map((row) => row['id'])).toEqual(ids.slice(2, 4))
    expect(await engine.nthKey(table, ['id'], { position: 3 })).toEqual([ids[2]])
    expect(await engine.nthKey(table, ['id'], { position: 99 })).toBeNull()

    // Copying the same chunk twice is what a crash between the chunk and the marker costs, and it
    // has to converge rather than raise.
    const chunk = await engine.keyRange(table, ['id'], { limit: 5 })
    await engine.copyIn(table, chunk)
    expect(await engine.count(table)).toBe(5)
  })

  it('keeps the bookkeeping tables append-only', async () => {
    const before = await engine.mapWatermark()
    await engine.recordMapVersion((before ?? 0) + 1, { modelVersion: model.version })
    expect(await engine.mapWatermark()).toBe((before ?? 0) + 1)
    // A stale row can never lower the bar: the watermark is a max, so a lower version written
    // afterwards changes nothing.
    await engine.recordMapVersion(1, { modelVersion: model.version })
    expect(await engine.mapWatermark()).toBe((before ?? 0) + 1)

    const marker = { materialization: 'Sample@ch', entity: 'Sample' }
    const start = await engine.backfillMarker(marker)
    await engine.recordBackfillMarker({ ...marker, rows: start + 7 })
    expect(await engine.backfillMarker(marker)).toBe(start + 7)
  })
})

/**
 * One statement straight over ClickHouse's HTTP interface, with no adapter in the way.
 *
 * Fifteen lines of transport in a test rather than a call through the thing under test, for the
 * reason the connection-cutting test opens its own `pg` client: the subject is what the adapter
 * reports, so the control has to come from somewhere else. Without it, "FINAL collapses the key"
 * would be asserted against a reader that also collapses it.
 */
/**
 * Drop the tables a fixture is about to create, in each engine.
 *
 * Not a nicety. These suites share a database with the Python live tests and with each other, and
 * `CREATE TABLE IF NOT EXISTS` keeps a table of that name whatever shape it is in - so without
 * this, the first language to run decides the schema and the second one's create path never runs.
 */
async function dropClickHouse(tables: readonly string[]): Promise<void> {
  for (const table of tables) {
    await raw(`DROP TABLE IF EXISTS \`${table.replace(/`/g, '``')}\``)
  }
}

async function dropPostgres(tables: readonly string[]): Promise<void> {
  const { Client } = await import('pg')
  const client = new Client({ connectionString: PG_DSN as string })
  await client.connect()
  try {
    for (const table of tables) {
      await client.query(`DROP TABLE IF EXISTS "${table.replace(/"/g, '""')}" CASCADE`)
    }
  } finally {
    await client.end()
  }
}

async function raw(sql: string): Promise<string> {
  const url = new URL(CH_DSN as string)
  const { request } = await import('node:http')
  return new Promise<string>((resolve, reject) => {
    const req = request(
      {
        host: url.hostname,
        port: Number(url.port),
        method: 'POST',
        path: `/?database=${url.pathname.replace(/^\//, '')}&query=${encodeURIComponent(sql)}`,
        headers: {
          'X-ClickHouse-User': decodeURIComponent(url.username) || 'default',
          'X-ClickHouse-Key': decodeURIComponent(url.password),
        },
      },
      (response) => {
        const chunks: Buffer[] = []
        response.on('data', (chunk: Buffer) => chunks.push(chunk))
        response.on('end', () => {
          const text = Buffer.concat(chunks).toString()
          const status = response.statusCode ?? 0
          if (status >= 200 && status < 300) resolve(text)
          else reject(new Error(`ClickHouse answered ${status}: ${text.trim()}`))
        })
      },
    )
    req.on('error', reject)
    req.end('')
  })
}

async function rawCount(table: string, id?: string): Promise<number> {
  const where = id === undefined ? '' : ` WHERE id = '${id}'`
  return Number((await raw(`SELECT count() FROM \`${table}\`${where}`)).trim())
}

describe.skipIf(!CH_DSN)('the ClickHouse adapter', () => {
  const { model, map } = fixture()
  const layout = map.groups['Sample']?.derived[0]?.layout
  let engine: ClickHouseEngine

  beforeAll(async () => {
    engine = new ClickHouseEngine(CH_DSN as string)
    await engine.connect()
  // **Dropped before created, which the Python side has always done and this file never did.**
  // These suites share one database with the Python live tests, and `CREATE TABLE IF NOT EXISTS`
  // keeps whatever is already there - so whichever language ran first decided the shape and the
  // other one's create path was never exercised. Invisible until the adapters started verifying
  // column *types* on 7 September 2026, at which point a `DateTime64(3, 'UTC')` left by an older
  // run was refused here. The refusal was right; the fixture was wrong.
    await dropClickHouse(Object.values(layout!.tables))
    await engine.ensureSchema(layout!, { keys: KEYS })
  })
  afterAll(async () => {
    await engine.close()
  })

  it('says which server it is', () => {
    // Not decoration: this is the exchange the handshake bound exists for, so a test that never
    // read its result would leave the bound guarding nothing observable.
    expect(engine.version).toMatch(/^\d+\./)
  })

  it('round-trips every type the layout declares', async () => {
    const id = randomUUID()
    await engine.insert('sample', sample(id))
    const back = await engine.get('sample', { id })
    expect(back).not.toBeNull()
    expect(back?.['big']).toBe(9_007_199_254_740_993n)
    expect(back?.['money']).toBe('12.34')
    expect(back?.['day']).toBe('2026-08-27')
    expect((back?.['at'] as Date).toISOString()).toBe('2026-08-27T12:00:00.000Z')
    expect(back?.['label']).toBe('zażółć gęślą jaźń')
    expect(back?.['flag']).toBe(true)
  })

  it('refuses to pretend it has a transaction', async () => {
    // A no-op that ran the callback would let the writes proceed and let the caller believe they
    // were atomic, which is being lied to at the worst possible moment.
    expect(() => engine.transaction(async () => undefined)).toThrow(EngineError)
    expect(() => engine.transaction(async () => undefined)).toThrow(
      'will not pretend to start one',
    )
  })

  it('overwrites rather than refusing a repeated key, and FINAL makes that visible at once', async () => {
    // The divergence that cannot be removed, only chosen: a MergeTree does not enforce uniqueness
    // on its ORDER BY, so the newest row for a key wins. `FINAL` is what makes the collapse visible
    // immediately rather than after a background merge - measured here rather than assumed, because
    // without it a count over a key written twice is simply wrong.
    const id = randomUUID()
    // **Merges stopped for the duration, and that is not tidiness.** The measurement below is that
    // two inserts really are two rows until something collapses them, and a background merge is
    // exactly that something: with merges running this assertion passed four runs in five and
    // failed the fifth, which is the shape of test that teaches a team to rerun rather than to
    // read. The reference implementation measured the same pair the same way.
    await raw('SYSTEM STOP MERGES `sample`')
    try {
      await engine.insert('sample', { ...sample(id), label: 'first' })
      await engine.insert('sample', { ...sample(id), label: 'second' })
      const back = await engine.get('sample', { id })
      expect(back?.['label']).toBe('second')

      // The observable that is deterministic: the count. `get` cannot show this - it returns a
      // single row either way, and *which* one is whichever part the scan reaches first, measured
      // to be the newest on this server. That is why the FINAL in `get` is held by a check over
      // the source instead (`adapters.test.ts`), and why removing it passed every live test.
      expect(await rawCount('sample', id)).toBe(2)
      expect(await engine.count('sample')).toBeLessThan(await rawCount('sample'))

      const rows = await engine.keyRange('sample', ['id'], { after: [id], upto: [id] })
      expect(rows).toHaveLength(0)
      const exact = await engine.keyRange('sample', ['id'], { upto: [id] })
      expect(exact.filter((row) => row['id'] === id)).toHaveLength(1)
    } finally {
      await raw('SYSTEM START MERGES `sample`')
    }
  })

  it('keeps the bookkeeping tables append-only, by the same mechanism as the other engine', async () => {
    const before = await engine.mapWatermark()
    await engine.recordMapVersion((before ?? 0) + 1, { modelVersion: model.version })
    expect(await engine.mapWatermark()).toBe((before ?? 0) + 1)
    const marker = { materialization: 'Sample@pg', entity: 'Sample' }
    const start = await engine.backfillMarker(marker)
    await engine.recordBackfillMarker({ ...marker, rows: start + 3 })
    expect(await engine.backfillMarker(marker)).toBe(start + 3)
  })

  it("survives a table name with a quote in it", async () => {
    // Half of the defect CodeQL found, measured. `verifySchema` lists the table names it is looking
    // for as SQL literals, and the first version inlined an escaper that handled a quote and
    // **not** a backslash. A table name is not always ours: a hand-written map is a supported
    // mode, and an unhashed entity name can contain anything a client typed.
    //
    // Only the quote, and the reason is worth stating: a backslash inside a backtick-quoted
    // identifier is reinterpreted by the server, so a table created with one in its name comes back
    // under a *different* name rather than as a syntax error - which makes a live table the wrong
    // instrument for that half. It is pinned directly instead, in `adapters.test.ts`, along with
    // the rule that there is only one escaper to get wrong.
    const table = `odd'name${randomUUID().slice(0, 8)}`
    const layoutForOddName = {
      tables: { Sample: table },
      columns: layout?.columns ?? {},
      indexes: [],
      partitionBy: {},
    }
    // The assertion is that this returns at all: `ensureSchema` creates the table and then reads
    // `system.columns` back, which is the query the escaping is in.
    await engine.ensureSchema(layoutForOddName, { keys: KEYS })
    const id = randomUUID()
    await engine.insert(table, sample(id))
    expect((await engine.get(table, { id }))?.['id']).toBe(id)
    await raw(`DROP TABLE ${'`'}${table.replace(/`/g, '``')}${'`'}`)
  })

  it('refuses a key value it cannot render rather than rendering it wrong', async () => {
    // The rendering is total: every kind this library can hold has a branch, and an unknown kind
    // throws. A value that reached a query as an unquoted [object Object] would be a syntax error
    // at best and a different query at worst.
    await expect(engine.get('sample', { id: { nested: true } })).rejects.toThrow(
      'cannot be rendered for ClickHouse',
    )
  })
})

describe.skipIf(!PG_DSN || !CH_DSN)('the two engines agree', () => {
  const { model, map } = fixture()
  let postgres: PostgresEngine
  let clickhouse: ClickHouseEngine

  beforeAll(async () => {
    postgres = new PostgresEngine(PG_DSN as string)
    clickhouse = new ClickHouseEngine(CH_DSN as string)
    await postgres.connect()
    await clickhouse.connect()
    const pgLayout = map.groups['Sample']?.source.layout as never as { tables: Record<string, string> }
    const chLayout = map.groups['Sample']?.derived[0]?.layout as never as {
      tables: Record<string, string>
    }
  // **Dropped before created, which the Python side has always done and this file never did.**
  // These suites share one database with the Python live tests, and `CREATE TABLE IF NOT EXISTS`
  // keeps whatever is already there - so whichever language ran first decided the shape and the
  // other one's create path was never exercised. Invisible until the adapters started verifying
  // column *types* on 7 September 2026, at which point a `DateTime64(3, 'UTC')` left by an older
  // run was refused here. The refusal was right; the fixture was wrong.
    await dropPostgres(Object.values(pgLayout.tables))
    await dropClickHouse(Object.values(chLayout.tables))
    await postgres.ensureSchema(map.groups['Sample']?.source.layout as never, { keys: KEYS })
    await clickhouse.ensureSchema(map.groups['Sample']?.derived[0]?.layout as never, { keys: KEYS })
  })
  afterAll(async () => {
    await postgres.close()
    await clickhouse.close()
  })

  it('returns the same value, in the same JavaScript type, from either engine', async () => {
    // The most important test in this file, and the one nothing else covers: two divergences were
    // living in exactly this gap in the reference implementation - a naive datetime two hours
    // apart, and a column that could not be compared at all because one driver returned an aware
    // value and the other a naive one.
    const id = randomUUID()
    const row = sample(id)
    await postgres.insert('sample', row)
    await clickhouse.insert('sample', row)

    const fromPg = await postgres.get('sample', { id })
    const fromCh = await clickhouse.get('sample', { id })
    expect(fromPg).not.toBeNull()
    expect(fromCh).not.toBeNull()

    for (const column of Object.keys(row).sort()) {
      const here = fromPg?.[column]
      const there = fromCh?.[column]
      expect(typeof here, `${column}: the two engines disagree about the type`).toBe(typeof there)
      if (here instanceof Date) {
        expect((there as Date).toISOString(), `${column}`).toBe(here.toISOString())
      } else {
        expect(there, `${column}`).toEqual(here)
      }
    }
  })

  it('opens the direction that used to truncate, because it no longer does', async () => {
    // PostgreSQL stored `timestamptz` to six sub-second digits and ClickHouse to three, so this
    // direction changed every value with more precision than that - silently, because the insert
    // succeeds. A walkthrough running the migration phases in order found `DUAL_WRITE` doing it on
    // every write, one phase *before* the gate that refuses the copy: measured, `09:30:15.123456`
    // came back from PostgreSQL unchanged and from ClickHouse as `09:30:15.123`.
    //
    // The refusal moved to the session, which was right, and then the pair stopped existing. The
    // three digits had been chosen against a comparison with plain `DateTime` rather than with the
    // engine beside it; both render six now. This assertion is the reverse of what it was, and it
    // is the one worth keeping: a transactional group in PostgreSQL with an analytical copy in
    // ClickHouse is the shape this product is sold on, and it must open.
    const run = randomUUID().replace(/-/g, '')
    const session = await Session.open(model, loadMap(fanOutMap('pg', run), { model }), {
      'pg-main': postgres,
      'ch-1': clickhouse,
    })
    expect(session.placement.groups['Sample']?.alsoWrite.length).toBeGreaterThan(0)
  })

  it('moves a group in the direction that does not, and verify says it landed', async () => {
    // Tier 2's own end-to-end, in the direction the gate allows: three digits into six is a
    // widening. Two engines with different key semantics and different idempotence mechanisms -
    // ON CONFLICT DO NOTHING against a ReplacingMergeTree collapse - in one migration.
    const { backfill, verify } = await import('../src/migration.js')
    const run = randomUUID().replace(/-/g, '')
    const migrating = await Session.open(model, loadMap(fanOutMap('ch', run), { model }), {
      'pg-main': postgres,
      'ch-1': clickhouse,
    })
    await migrating.ensureSchema()
    await migrating.save('Sample', sample(randomUUID()))

    const progress = await backfill(migrating, 'Sample', { chunkRows: 3 })
    expect(progress.complete).toBe(true)
    const report = await verify(migrating, 'Sample', { chunkRows: 3 })
    expect(
      report.matched,
      `verify found differences: ${JSON.stringify(report.differences.slice(0, 3))}`,
    ).toBe(true)
    // And the gate is a gate: it counted chunks rather than reporting a vacuous pass.
    expect(report.chunksCompared + report.tailRowsRead).toBeGreaterThan(0)
  })

  /**
   * The fixture's map with a fan-out, from whichever engine is named as the source, on tables of
   * its own.
   *
   * Hand-assembled here, which is a supported mode - a map you wrote yourself is the no-account
   * mode - and the reason it is hand-assembled is that the direction is the subject: the reference
   * planner would never issue the truncating one, so a vector cannot carry it and a test has to.
   *
   * **Fresh table names and fresh materialisation ids per run.** The first version reused the
   * fixture's names and passed once: on the second run the source held the previous run's rows and
   * the target held a progress marker from it, so `verify` reported rows as absent that a backfill
   * had already been told it had copied. Both halves of that are state a test set up and did not
   * own - and the failure looked exactly like a real lost-row defect, which is the worst way for a
   * migration test to be wrong.
   */
  function fanOutMap(source: 'pg' | 'ch', run: string): Record<string, unknown> {
    const document = JSON.parse(readFileSync(join(VECTOR, 'map.json'), 'utf8')) as {
      contract: number
      groups: Record<string, Record<string, unknown>>
      map_version: number
    }
    const group = document.groups['Sample'] as Record<string, unknown>
    const rename = (body: Record<string, unknown>, role: string): Record<string, unknown> => {
      const layout = body['layout'] as Record<string, unknown>
      return {
        ...body,
        id: `Sample@${role}_${run}`,
        layout: { ...layout, tables: { Sample: `sample_${role}_${run}` } },
      }
    }
    const pg = rename(group['source'] as Record<string, unknown>, 'pg')
    const ch = rename((group['derived'] as Record<string, unknown>[])[0] as Record<string, unknown>, 'ch')
    const [from, to] = source === 'pg' ? [pg, ch] : [ch, pg]
    document.contract = 2
    document.map_version = 2
    const asSource = { ...from }
    delete asSource['lag_budget_ms']
    group['source'] = asSource
    group['derived'] = [{ ...to, lag_budget_ms: 30000 }]
    group['also_write'] = [String(to['id'])]
    return document
  }
})
